# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e04a6be6e2b7b9c851c707c1faa40369f8f3a65c0f25a90abdf7a23900a5d9691d7470b32478ddbe547dcb59ac96bb25ebe0329847990c5eb9c64b5371d9313

test:
  secret_key_base: 0f219743f1ebd74dd9d67b5dbb77929d1d89903c7fe3f1ad2c8d64925847df35f14ced230d46480c6c43a2c4b3cb039e1cadadaa0763efb5aee3a02e6b5f1ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
